### ISSUE TITLE
Supermarket Simulator: QA Feedback

### ISSUE THREAD

**Issue by MrS4turn** [WarpWorld/CCPack-PC-SupermarketSimulator#1]
Bugs:

Despawn Customer - while you are checking out someone and they despawn, other customers are no longer able to move through the line. Will need to detect if you checking someone out before 
Throw and maybe Drop - some weird state happened that forced the item of their hand but the ui was bugged and didnt let them click on anything else.

New Effects:
Shuffle number pad
Shuffle cash register 

Ideas:
Hook customer messages to TTS
Hook customer messages to twitch chat

**Comment by jaku** [comment]
despawn customer fixed in 713cdf1f103b0467aa6ac597dc30054f161eba4d

**Comment by jaku** [comment]
![image](https://github.com/WarpWorld/CCPack-PC-SupermarketSimulator/assets/102187/0eb9c1e1-2913-473a-a5a8-370450974c01)

notes on throw/drop effect. it does the action, but the UI doesn't update, so the state prolly doesn't update to the player.

digging into it, but in the screenshot the box was thrown by the door but my ui still thinks i can drop it.

**Comment by jaku** [comment]
fixed throw in 1e14f31a9dd1e6ed040981fc733492c753c25d86

drop is better, still not perfect.

originally we were just dropping the item though another method, but that didn't disable the UI or "unlink" it from the player state.

now we drop the box, and we call the "onDrop()" function for the player, which moves the state slightly and changes the UI to now just require a click to drop it.

its less likely to bug out but if a streamer presses esc, it will go back to the original issue.

so still digging in a little bit more here.

**Comment by MrS4turn** [comment]
Big improvements and new effects! Closing this for now.
